/*
 * Copyright (C) 2020 Gabriel Duta
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

package com.gabriel.file_random_number;

import java.awt.Color;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 * Questa classe gestisce la GUI principale dell'applicazione in cui è presente
 * la gestione del file con i dati e le statistiche dei dati.
 * 
 * @author Gabriel Duta
 * @version 2.0
 */
public class GUI_dati extends javax.swing.JFrame {

    Color defaultBackground;
    /**
     * Creates new form GUI_dati
     */
    public GUI_dati() {
        initComponents();
        this.setLocation(500, 200);
        
        // collegamento dell'ascoltatore del bottone Open Fie all'ascoltatore del MenuItem
        openFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openActionPerformed(evt);
            }
        });
        
        textArea.setEditable(false);
        
        // setup jLable filePath
        filePath.setForeground(Color.gray);
        filePath.setEditable(false);
        
        defaultBackground = this.getContentPane().getBackground();
        darkMode(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        generateFile = new javax.swing.JToggleButton();
        openFile = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        media = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        minimo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        massimo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        delta = new javax.swing.JLabel();
        filePath = new javax.swing.JTextField();
        computeButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        open = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        exit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenu3 = new javax.swing.JMenu();
        help = new javax.swing.JMenuItem();
        about = new javax.swing.JMenuItem();

        fileChooser.setFileFilter(new MyCustomFilter());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Random numbers from file analisis");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        generateFile.setText("Generate file");
        generateFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateFileActionPerformed(evt);
            }
        });

        openFile.setText("Open file");

        jLabel1.setText("Average:");

        media.setText("0");

        jLabel2.setText("Minimum:");

        minimo.setText("0");

        jLabel4.setText("Maximum:");

        massimo.setText("0");

        jLabel3.setText("Delta:");

        delta.setText("0");

        filePath.setText("File Path");

        computeButton.setText("Compute");
        computeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computeButtonActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        open.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        open.setText("Open");
        open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openActionPerformed(evt);
            }
        });
        jMenu1.add(open);
        jMenu1.add(jSeparator1);

        exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jMenu1.add(exit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Compute");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Dark mode");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jCheckBoxMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("?");

        help.setText("Help");
        jMenu3.add(help);

        about.setText("About");
        jMenu3.add(about);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delta, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(computeButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(media, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(minimo, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                                .addComponent(massimo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(filePath, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(openFile)
                        .addGap(18, 18, 18)
                        .addComponent(generateFile))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generateFile)
                    .addComponent(openFile)
                    .addComponent(filePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(computeButton)
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(media))
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(minimo))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(delta))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(massimo))
                        .addGap(26, 26, 26))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Metodo che apre la finestra del file chooser e mostra il contenuto del file scelto
     * nella textArea.
     * 
     * @param evt 
     */
    private void openActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openActionPerformed
        int returnVal = fileChooser.showOpenDialog(this); // apre la finestra del file chooser
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile(); // passa all'istanza file il file scelto nel file chooser
            try {
              // Mostra il contenuto del file e il suo path
              textArea.read( new FileReader( file.getAbsolutePath() ), null );
              filePath.setText(file.getAbsolutePath());
            } catch (IOException ex) {
              System.out.println("problem accessing file"+file.getAbsolutePath());
            }
        } else {
            System.out.println("File access cancelled by user.");
        }
    }//GEN-LAST:event_openActionPerformed
    
    
    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    /**
     * Genera un file riempiendolo con 100 numeri casuali compresi tra -30 e 40.
     * I file generati hanno nome simile ma terminano con un numero crescente.
     * @param evt 
     */
    private void generateFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateFileActionPerformed
        int j = 0;
        String nomeF = "RandomNumbers";
        BufferedWriter bw;
        
        // Le seguenti righe servono a creare i file generati dal jButton "Generate File" mettendoli
        // in ordine crescente, tenendo in considerazione anche i file già presenti nella directory.
        File inDir[] = new File("./").listFiles(); // mette nel vettore tutti i file presenti nella directory.
        for (File file : inDir) {
            String nome = file.getName();
            if(nome.indexOf(nomeF) == 0) { // controlla che il nome del file inizi con "RandomNumbers"
                try { // Questo try permette di controllare che nel nome del file non ci siano altri caratteri, in quel
                      // caso non verrebbe considerato nella conta.
                      // Inoltre trova il numero maggiore perchè inDir non ha i file ordinati.
                    int num = Integer.valueOf(nome.substring(nome.lastIndexOf(nomeF) + 13, nome.indexOf(".na")));
                    if(num > j)
                        j = num;
                } catch (NumberFormatException e) {}
            }
        }
        
        File f = new File("./" + nomeF + (j + 1) + ".na");
        Random rnd = new Random();
        try { // riempe il file con 100 numeri casuali
            bw = new BufferedWriter(new FileWriter(f));
            for (int i = 0; i < 100; i++)
                bw.write(Integer.toString((rnd.nextInt(70) - 30)) + "\n");
            bw.flush();
            textArea.read(new FileReader(f), null);
        } catch (IOException ex) {
            Logger.getLogger(GUI_dati.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        filePath.setText(f.getAbsolutePath());
    }//GEN-LAST:event_generateFileActionPerformed

    /**
     * Questo ascoltatore calcola la media, il maggiore, il minore e il delta dei numeri
     * presenti nel file.
     */
    private void computeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computeButtonActionPerformed
        int somma = 0, min = 41, max = -31, delta, i;
        
        // operazioni per l'analisi del file
        String s[] = textArea.getText().split("\n");
        for (String string : s) {
            i = Integer.valueOf(string);
            somma += i;
            if(i < min) min = i;
            if(i > max) max = i;
        }
        delta = max - min;
        
        // modifica delle jLabel con i risultati
        media.setText(Double.toString(somma / s.length));
        minimo.setText(Integer.toString(min));
        massimo.setText(Integer.toString(max));
        this.delta.setText(Integer.toString(delta));
    }//GEN-LAST:event_computeButtonActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        computeButton.doClick();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
        if(jCheckBoxMenuItem1.isSelected())
            darkMode(true);
        else
            darkMode(false);
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    private void darkMode(boolean state) {
        if(state) {
            this.getContentPane().setBackground(Color.darkGray.darker());
            delta.setForeground(Color.white);
            jLabel1.setForeground(Color.white);
            jLabel2.setForeground(Color.white);
            jLabel3.setForeground(Color.white);
            jLabel4.setForeground(Color.white);
            massimo.setForeground(Color.white);
            media.setForeground(Color.white);
            minimo.setForeground(Color.white);
        }
        else {
            this.getContentPane().setBackground(defaultBackground);
            delta.setForeground(Color.black);
            jLabel1.setForeground(Color.black);
            jLabel2.setForeground(Color.black);
            jLabel3.setForeground(Color.black);
            jLabel4.setForeground(Color.black);
            massimo.setForeground(Color.black);
            media.setForeground(Color.black);
            minimo.setForeground(Color.black);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_dati.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_dati.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_dati.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_dati.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_dati().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem about;
    private javax.swing.JButton computeButton;
    private javax.swing.JLabel delta;
    private javax.swing.JMenuItem exit;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JTextField filePath;
    private javax.swing.JToggleButton generateFile;
    private javax.swing.JMenuItem help;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel massimo;
    private javax.swing.JLabel media;
    private javax.swing.JLabel minimo;
    private javax.swing.JMenuItem open;
    private javax.swing.JToggleButton openFile;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}

/**
 * Classe per abilitare il filtraggio dei file non desiderati e abilitare solo i
 * .java e i .txt
 * 
 * @author Gabriel Duta
 * @since 1.0
 */
class MyCustomFilter extends javax.swing.filechooser.FileFilter {
    @Override
    public boolean accept(File file) {
        // Allow only directories, or files with ".java" extension
        return file.isDirectory() || file.getAbsolutePath().endsWith(".na");
        // .na sta per Number Analizer
    }
    @Override
    public String getDescription() {
        // This description will be displayed in the dialog,
        // hard-coded = ugly, should be done via I18N
        return "Number Analizer files (*.na)";
    }
    
}